// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace RPGGameplayTags
{
	/*Shared Tags*/
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Hit);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile);

	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_IdentityGain);

	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Invincible);

	/** Game Data tags **/
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_SurvivalGameModeMap);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_LobbyMap);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_MainMenuMap);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_BossBattleMap);

	/* UI Widget Tags */
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_Layer_Game);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_Layer_GameMenu);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_Layer_Menu);
	PROJECT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_Layer_Modal);
}
